#!/usr/bin/env bash
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# print function
cprint() {
  local color=$1
  local text=$2
  local NOC=$NC
  echo -e "${color}" "${text}" "${NOC}"
}

# build function along with zipping

build () {
  cprint "$YELLOW" "start building the app"
  npm run build >> building_log.log
  cprint "$RED" "Please check the building log and wait a moment for zip the app"
  sleep 2
  cprint "$CYAN" "Zipping the app wait a few sec please"
  zip -r App.zip build >> zipping_log.log
}
# clean the logs

clean () {
  out=$(echo $?)
  if [ "$out" -eq 0 ]; then
    rm zipping_log.log building_log.log
    rm -rf build
    notify-send "op is done"
  else
    notify-send "op failed"
  fi
}


build
clean

